version: '3.8'

services:
  clamav-backend:
    build:
      context: ./clamav-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - clamav-db

  clamav-guard:
    build:
      context: ./clamav-guard
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - clamav-backend

  clamav-ui:
    build:
      context: ./clamav-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"

  clamav-db:
    image: postgres:13
    environment:
      POSTGRES_DB: clamav_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: